experiment_network = "10.1.0.0/16"
unfiltered_ports = [22, 53, 10000, 58080]
# we assume there (at most) as many nodes as there are interfaces on the
# mediator and that they follow this naming scheme for DNS/hostnames.
node_name_format = "n{}" # n1, n2, n3, etc.
bucket_interval_ms = 10

# we assume nodes' clocks are synchronized to within this many milliseconds
clocks_synchronized_to_within_ms = 100
statistics_print_interval_secs = 5

nfqueue_queue_num = 1
nfqueue_max_len = 131072 # number of packets to queue
nfqueue_select_timeout_ns = 10000 # 0.01ms

# Adaptive Nemesis configuration
nemesis_schedule_duration_ms    = 30000 # how long is a nemesis "run"?
nemesis_schedule_interval_ms    = 2500   # there is a "choice" every X ms
nemesis_reset_duration_ms       = 2500  # how long do we wait after a reset before starting a new run?

mediator_log_filename = "/tmp/mediator.log"
shiviz_log_filename = "/tmp/shiviz.log"
event_log_filename = "/tmp/events.log"
iptables_rules_filename = '/tmp/iptables-rules.txt'

mediator_store_folder = "mediator" # relative to the Jepsen test directory
transmit_pcap_filename = "transmit.pcap"
receive_pcap_filename = "receive.pcap"
drop_pcap_filename = "drop.pcap"

# ===================================================================
# New MMEventHistory Configuration
# ===================================================================
num_nodes = 7
symmetry_reduction_scheme = "None"  # Options: "None", "Sort", "Merge"
                                    # "Merge" is not implemented yet
categorize_message_by_data = true
use_old_summary_as_reward = false

# ===================================================================
# New MMEventHistory Global State Configuration
# ===================================================================
# [mmeventhistory_global]
global_split_vc_mm = false
global_record_sender_partition = false

# [mmeventhistory_global.partition_scheme]
global_num_local_event_partitions = 1
global_local_event_partition_len = 100
global_num_message_events_partitions = 1
global_message_event_partition_len = 100

# [mmeventhistory_global.event_kind_config]
global_num_local_event_kinds = 1
global_num_message_event_kinds = 1

# ===================================================================
# New MMEventHistory Per-Event State Configuration
# ===================================================================
# [mmeventhistory_per_event]
per_event_split_vc_mm = false
per_event_record_sender_partition = false

# [mmeventhistory_per_event.partition_scheme]
per_event_num_local_event_partitions = 1
per_event_local_event_partition_len = 1
per_event_num_message_events_partitions = 1
per_event_message_event_partition_len = 1

# [mmeventhistory_per_event.event_kind_config]
per_event_num_local_event_kinds = 1
per_event_num_message_event_kinds = 1

# ===================================================================
# New Similarity, Record, and Reward Configurations
# ===================================================================
# [similarity]
mm_use_absolute_similarity_threshold = false
mm_event_history_global_similarity_threshold = 0.5
mm_event_history_per_event_similarity_threshold = 0.5
mm_event_history_global_similarity_threshold_vc = 0.3
mm_event_history_global_similarity_threshold_mm = 0.3
mm_event_history_per_event_similarity_threshold_vc = 0.3
mm_event_history_per_event_similarity_threshold_mm = 0.3
# Note that for the a := old similarity_threshold, similar <=> (# equal MinHash values) / (# total hashers) >= a
# However, for the b := new similarity_threshold, similar <=> (L1 diff between message matrices) <= before
# In a nutshell, the direction of applying the similarity thresholds is opposite

# [record_config]
record_global_mm_state_only_on_reward_reporting = true
global_mm_state_record_interval = 100
record_per_event_mm_state = true
per_event_mm_state_record_interval_normal = 10
per_event_mm_state_record_interval_special = 100 # Not used yet
special_event_threshold = 20 # Not used yet

# [reward_config]
reward_on_global_state_change = 1.0
reward_on_per_event_state_change = 0.8
use_cool_down_factor = true
cool_down_threshold = 40